# Global config
global:
  scrape_interval: 15s        
  evaluation_interval: 15s    

# Alertmanager 
alerting:
  alertmanagers:
    - static_configs:
        - targets: []         


scrape_configs:
  
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  
  - job_name: "node_exporter"
    static_configs:
      - targets: ["localhost:9100"]
